### PR TITLE
Homework and Tutorial 6

### PR DESCRIPTION
**Pull request by MatthewYu06**

### CODE REVIEW

**Comment by MatthewYu06** [comment]
Homework:
- Mostly a direct port from last year at this point
- Q9/10: Perhaps remove since we’re not covering formal hypothesis testing?
- Kept bonus material at end bonus

Tutorial:
- Pulled example out of week 4 demo from last year, using gratitude dataset. I can pretty easily switch the example if you'd prefer something else, I just used this example to get my ideas down
- @pointOfive @mistryrohan I'm a bit stumped about how to incorporate the gender disparity paper tutorial materials, which include a presentation and some follow up discussion to the Rosalind Franklin homework. 
    - The follow-up discussion requires you to have read through the Rosalind Franklin homework questions and is short, maybe we could squeeze it into Rohan's tutorial corresponding to that week's homework. 
    - Not sure where to do the presentation, the one/two sample hypothesis test presentation is introduced in week 6 and presumably presented in week 7(along with project introduction). Maybe we could introduce gender disparity paper at end of week 5 tutorial, and have presentations start at the beginning of week 6 (and cut down on the week 6 worked example, shouldn't be too hard since lots of similarities between one and two sample hypothesis test). Would be pretty tight on time though and lots of work for student in week 5 (tutorial assignment + presentation prep).

**Comment by pointOfive** [comment]
### HW
- expanded the header explaining MarkUs autotesting and marking based on updated iterations of that which were made through the first round of content creation
- Q0: I need to double check that "\%" prints out correctly in MarkUs... probably does :) 
  - printout generally looked great; although, I revised the prompt and expanded things little bit to better emphasize the important aspects of this prompt and better address the prompt
- Q1: minor edits
- Q2: I think adding line breaks is helpful and do so here and will continue to do so
- Q3: small edits
- Q4: p-value calculation was accidentally one sided: I may have made this mistake in my recording
  - revised what was a fairly good answer where I felt improvement was possible
  - My revision on the Q4 hint/explanation got me thinking that this (the general way we use an observed test statistic to critic if a null hypothesis might be wrong) should be emphasized in the week 6 tutorial
  - I think it's okay that we didn't do this in week 5 as there we're first emphasizing the process and routine of computing and using p-values
- Q5: trying to move the language more towards "evidence" statements 
  - Please change this to a multiple choice question, replacing the jpg image I added with the following:

  A. $0.10 < \text{p-value}$ no evidence against the null hypothesis
  
  B. $0.05<\text{p-value}<0.10$ weak evidence against the null hypothesis

  C. $0.01<\text{p-value}<0.05$ moderate evidence against the null hypothesis

  D. $0.001<\text{p-value}<0.01$ strong evidence against the null hypothesis

  E. $\text{p-value}<0.001$ very strong evidence against the null hypothesis

- Q5: keep the hint the same, but reword the prompt so it's just a multiple choice question (with no restated null hypothesis summary... they've already done that above so it's okay to not do it again)
  - I have "hidden" the ABCD answers in the `test` variables for other multiple choice questions: please do that for this one as well
- Q6 is fun/good

#### new questions requested

- new Q7(s)[? it is probably going to be necessary to make this into multiple questions]: have students use a couple non-parametric tests and a parametric p-value calculation
  - `scipy.stats.median_test` which assumes the medians of the two groups are identical 
  - `scipy.stats.mannwhitneyu` which (more strongly) assumes "no actual difference between groups"
  - `scipy.stats.ttest_ind` which assumes the means of the two groups are identical and that the samples come from normally distributed populations
- have students answer multiple choice questions about which of these are nonparametric/parametric and why: the answers should be in the homework explanation/guidance already, so these should just be a question of making some correct explanations and some mixed up explanations
- I would also like a question that reminds students of the code based on `scipy.stats.binom` for one-sample p-values for proportions problems; and `scipy.stats.ttest_1samp`; and helps/asks them to differentiate these from the newly introduced tests up above. This should again just be a question of making some correct explanations and some mixed up explanations.

- new Q8: create a confidence interval of the difference between the two groups. Guide the students to use a random number seed (just as you've done nicely in Q8) and how a two-sample interval gets constructed with bootstrapping and create an autotest to confirm this.

#### back to original questions

- original Q7: please reformulate the prompt and answer to be analogous to the reformulation of Q0 (but without hints this time). [I.e., use the Q0 form and replace the parts with pieces from Q7]
  - I like that the one-sided hypothesis test is introduced here, and we should indeed do this; however, a hint/explanation as to how this works needs to be introduced and included with this question. We need to explain what we're asking them to do and how it's different.  This has to do with no longer needing the `abs` treatment in the "as or more extreme" calculation.
  - You'll need to determine how to alter the updated statement of the prompt and/or other problem information to help guide the students as to the difference between what you're asking here and the original two-sided testing style that they're more familiar with
  - It's a really good problem to introduce this; but, we need to make this problem an opportunity to help explain what's actually happening here (even if we may have done a little bit of this previously)
- original Q8: reworked prompt slightly as I think it didn't quite state everything that was asked for
  - I've added a hint that I think is necessary/helpful here
- original Q9: keep this but convert it to the style of Q5 (and use the ABCDE options I provide above)
- original Q10: keep this; but, we need to explain what Type I and II errors are. We need an explanation section that reminds students that if we make a formal choice "to reject" or "fail to reject" then we might make an error. Then ask the students the question :)
- original Q11: looks good
- Optional Q12-Q15: these feel like they might better go in the tutorial. Just leave them in the notebook for now and I'll make a final determination on how to use them soon.

**Comment by pointOfive** [comment]
- Q0/1/2/3/4: smaller edits -- just me revising per my sensibilities as I read through things again
- Q5: did catch an error in the answer (likely that I myself made initially)
- Q6: good
- Q7: edited; but, this was great just what I was looking for here
- Q8: good question; hid answer and provided hint
- Q9: good again; but, as with Q7, I've clarified these tests with some extensive hints, which I think are important and potentially helpful for the the students to have available... the homework is like an interactive reading assignment here that we can use to expose students to some advanced ideas that I am hoping will help students consolidate the easier bigger picture ideas of everything...
  - we'll see... it may only serve to separate the more advanced students from the students newer and less able to cope with the new concepts... but; hopefully, it will be a little better than that :)
  - Oh, `scipy.stats.mannwhitneyu` is different from "Wilcoxon Rank Sum test" (`scipy.stats.wilcoxon`): corrected/fixed this...
    - The former is for unpaired (independent) samples while the latter is for paired samples...
- Q10/11/12: all good -- went ahead and made the edits I'm looking for here myself since they're just rinse/wash/repeat kinda stuff from the last few questions and the template/structure just need to be reapplied to keep things uniform and consistent (per my current preferences)
- Q13 is looking very promising, and I expect to use this; but, that will likely just be rolled into Q14; because, I want to make sure the students play the exercise of characterizing evidence against the null hypothesis...
  - I've done with with my new Q13
- Q14: indeed; I've made a nice combination of the original Q13+Q14 that I'm quite pleased with -- very excellent per my wishes/intentions here
- Q15: edited for more clarity in my usual manner; however, this one was not actually doing the right thing...
  - Didn't provide a 90% CI
  - Made a CI around the sampling distribution of the null hypothesis rather than how this should actually be done... have a look
  - Needs `replace=False` to get bootstrapping... in the `.sample()` method...
  - Not terrible as an initial draft I suppose; but, this is really early stage as such given all the errors and I would hope content like this would be a little more polished in the future (speaking more generally)
- Q16: this was a good start; but, my feeling about it is a little bit different so I've made edits to put this problem in line with why thinking on this.
- Q17: I've combined this with Q18
- **Q18:  please create this problem to be analogous to Q15; but, perhaps make it a 95% confidence interval this time.**
  - Let's also ask the students to visualize the distribution of bootstrapped sample proportion differences
  - I think it's good to have you do this so that you can see the difference between the sampling distribution under the null hypothesis and compared to how to created two sample bootstrap confidence intervals :)
  - You don't need to provide any hints this time... hopefully they got them the first time around in Q15...
- Improved the Q19 test; but, will you make sure its working correctly?
- Q20: I thought up some improvements on this question prompt, I think
- I've removed all optional question: I do think these are more suited to tutorial discussions if we find we need to add some content into the tutorial...

So, then, do you have time to get this set up and running on MarkUs at this point?

**Comment by MatthewYu06** [comment]
made new Q18, modified Q17 answer structure, fixed general typos I caught

**Comment by MatthewYu06** [comment]
- modified Q13 option D to be inclusive of 0.001
- tested out MarkUs autotest, good for the most part
- for some reason, `anxiety_data` was not defined in the autotests even though `crash_data` was fine. Just ended up reassigning `anxiety_data` in the Q7 autotest, I think this looks fine

**Pull request merged**
